### ISSUE TITLE
User persisting in database

### ISSUE THREAD

**Issue by ArkaBando** [sunitk/multitenancy-dynamic-tenant#1]
User cannot be saved in database

**Comment by sunitk** [comment]
Please look at this piece of code in TenantDatabaseConfig.java

` @Bean(name = "tenantTransactionManager")
    public JpaTransactionManager transactionManager(
            EntityManagerFactory tenantEntityManager) {
        JpaTransactionManager transactionManager = new JpaTransactionManager();
        transactionManager.setEntityManagerFactory(tenantEntityManager);
        return transactionManager;
    }`

Try adding a @Qualifier to the EntityManagerFactory argument like this 

`@Bean(name = "tenantTransactionManager")
    public JpaTransactionManager transactionManager(@Qualifier("tenantEntityManagerFactory") 
            EntityManagerFactory tenantEntityManager) {
        JpaTransactionManager transactionManager = new JpaTransactionManager();
        transactionManager.setEntityManagerFactory(tenantEntityManager);
        return transactionManager;
    }`

This will ensure that the transaction manager and entity manager are very specifically connected.

Also in your save code in the Service class, ensure that the save method is annotated with @Transactional.

Let me know how it goes.

**Comment by ArkaBando** [comment]
I was hoping it would have worked in that way , I have created another Entity called task under tenant , while saving in in mysql database , changes are not reflecting in the database although id is incrementing as displayed in console .

@Test
	@Transactional("tenantTransactionManager")
	public void saveUser() {
		try {
		TenantContextHolder.setTenantId("tenant_1");
		Task task = new Task();
		task.setDesc("asd");
		task.setDone(false);
		task.setTargetDate(new Date());
		System.out.println("before =>"+task);
		//emf.getTransaction().begin();
		repo.save(task);
		repo.flush();
		System.out.println("after=>"+task);
		//emf.getTransaction().commit();
		
//		User user = new User();
//		user.setActive(true);
//		user.setPassword("ahdcvh");
//		user.setUsername("adsbj");
////		Role role = new Role();
////		role.setRole("admin");
////		role.setUsers(new HashSet<User>(Arrays.asList(user)));
////		user.setRoles(new HashSet<Role>(Arrays.asList(role)));
//		userService.save(user);
		} catch(Exception ex) {
			ex.printStackTrace();
		}
	}

**Comment by ArkaBando** [comment]
before =>Task [id=null, desc=asd, targetDate=Sun Jun 17 23:22:16 IST 2018, isDone=false]
after=>Task [id=2, desc=asd, targetDate=Sun Jun 17 23:22:16 IST 2018, isDone=false]

but rows are generated in mysql database , same for user and role

**Comment by ArkaBando** [comment]
Solved it should i push the solution

**Comment by sunitk** [comment]
Yes please.

**Comment by ArkaBando** [comment]
For testing purpose we need to manually select the tenant identifier and set it as 
private String initializeTenantIfLost(String tenantIdentifier) {
		if (TenantContextHolder.getTenant() == null) {

			/*SecurityContext securityContext = SecurityContextHolder.getContext();
			Authentication authentication = securityContext.getAuthentication();
			CustomUserDetails customUserDetails = null;
			if (authentication != null) {
				Object principal = authentication.getPrincipal();
				customUserDetails = principal instanceof CustomUserDetails ? (CustomUserDetails) principal : null;
			}
			TenantContextHolder.setTenantId(customUserDetails.getTenant());
		}*/

		 TenantContextHolder.setTenantId("tenant_1");

		if (tenantIdentifier != TenantContextHolder.getTenant()) {
			tenantIdentifier = TenantContextHolder.getTenant();
		}
		return tenantIdentifier;
	}

**Comment by ArkaBando** [comment]
Solved it in a hot fix way , though need better solution to make it testable.
