### ISSUE TITLE
new user is not getting save from code

### ISSUE THREAD

**Issue by ShaluKashyap1991** [sunitk/multitenancy-dynamic-tenant#13]
Hi Sunit,

Hope you are doing well.

While i was working in this project i found that when i was trying to add new tenant from Login Controller wherein i found that new user is not getting saved in databse.

Can you please check and get back to me if you can help.

 @RequestMapping("/user/index")
    public String userIndex(Model model) {
        getLoggedInUsername().ifPresent(f -> {
            model.addAttribute("userName", f);
        });
        getTenantName().ifPresent(d -> {
            model.addAttribute("tenantName", d);
        });
        
        User user = new User();
        user.setUsername("Shalu");
        user.setTenant("tenant_5");
        user.setPassword("hello");
        user.setActive(true);
        userService.save(user);
        
        return "user/index";
    }

Thank you:)

**Comment by sunitk** [comment]
Hi,

You cannot just save entities from a controller as you need transaction
support etc.
You should create a Service Layer which talks to the Repository layer.

So in your User entity please annotate it with @Entity.Then create a
repository like UserRepository with the annotation @Repository at the class
level. Finally you can write a Service layer which can call your repository
method.

Your service layer needs to be @Autowired into your MVC COntroller where
you can access the user methods.


Regards,
Sunit Katkar
https://sunitkatkar.blogspot.com

**Comment by ShaluKashyap1991** [comment]
Thank you so much sunit for response.

I have done it

**Comment by sunitk** [comment]
Closing this now.
