### ISSUE TITLE
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'tenantEntityManagerFactory'

### ISSUE THREAD

**Issue by morodev** [sunitk/multitenancy-dynamic-tenant#14]
i tried to download this project but when i try to boot from intellij i get this message

**Comment by sunitk** [comment]
This is not a issue or a bug that you cannot open this project in IntelliJ. It is a standard Spring Boot project and was created and developed using Spring Tool Suite. Maybe the latest version of Spring Boot does not exactly work with IntelliJ. If you read the blog post and understand what I am doing and sharing then you can create your own project from scratch using IntelliJ and Spring Boot. Then you can hand code the different classes, etc.

Also, you have just mentioned this one line of exception you see. Most likely you have not set up a proper connection with your database.

I recommend you read the complete blog post series on multi-tenancy by starting here 
[Building SaaS style multi-tenant web app with Spring Boot 2 and Spring Security 5 - Part 1](https://sunitkatkar.blogspot.com/2018/04/building-saas-style-multi-tenant-web.html)

I request you to not open such issues which are not really issues/bugs. So far, so many users have read my blog post and tried the code and it has worked for them. Please go through the comments in the blog.
