### ISSUE TITLE
Storing tenant information in thread local is not working for multiple threaded request against a same session as different instances of thread local are being generated for each request 

### ISSUE THREAD

**Issue by ArkaBando** [sunitk/multitenancy-dynamic-tenant#2]
Problem in persisting tenant info in thread local

**Comment by sunitk** [comment]
I need to spend some time and try. It should work but I dont know why it does not as you pointed out.

Can you tell me steps to reproduce?

Can you help me find a fix. It will help me and all others using this code.

**Comment by ArkaBando** [comment]
Try to save an employee or user through submitting a form , then the response will be committed and and threadlocal will be again intialized to empty for a new req thread.

**Comment by ArkaBando** [comment]
I have provided a fix through pull request .

**Comment by sunitk** [comment]
I have merged your pull request. Please take the latest code now.

**Comment by sunitk** [comment]
I am really grateful to ArkaBando for all his help in fixing issues which I did not think of!
