### ISSUE TITLE
Data source for tenants cannot handle concurrent request

### ISSUE THREAD

**Issue by ArkaBando** [sunitk/multitenancy-dynamic-tenant#3]
While load testing if only 5 user concurrently logging in the application it fails to get connection due to connection timeout.

**Comment by sunitk** [comment]
Hmmm.. I have followed what Hibernate suggests about configuring multi-tenancy.

Do you have any ideas to resolve this? Sorry that I am asking you to debug and fix my code.

**Comment by ArkaBando** [comment]
yup I will definitely but here is the idea of fall back mechanism which is a hot fix whenever such exception is happening create a new hibernate datasource dor the tenant and pool name will be per tenant.

**Comment by sunitk** [comment]
Do you have a fix like you did for the other issues?

**Comment by ArkaBando** [comment]
yes like i can say u the way or idea but  I need time for implementation . Like for database connection pooling pool name must be unique per tenant and we need to optimize below code in DataSourceBasedMultiTenantConnectionProviderImpl.

**Comment by ArkaBando** [comment]
@Override
	public Connection getAnyConnection() throws SQLException {
		return selectDataSource(TenantContextHolder.getTenant()).getConnection();
	}

	@Override
	public void releaseConnection(String tenantIdentifier, Connection connection) throws SQLException {
		try {
			connection.createStatement().execute("USE `test`;");
		} catch (SQLException e) {
			throw new HibernateException(
					"Could not alter JDBC connection to specified schema [" + tenantIdentifier + "]", e);
		}
		connection.close();
	}

	@Override
	public void releaseAnyConnection(Connection connection) throws SQLException {
		connection.close();
	}

	@SuppressWarnings("rawtypes")
	@Override
	public boolean isUnwrappableAs(Class unwrapType) {
		return false;
	}

	@Override
	public <T> T unwrap(Class<T> unwrapType) {
		return null;
	}

	@Override
	public boolean supportsAggressiveRelease() {
		return true;
	}

**Comment by sunitk** [comment]
@ArkaBando has already contributed the above fix via a PR (which is already merged). So closing this now.
