### ISSUE TITLE
master_tenant table in every tenant schema

### ISSUE THREAD

**Issue by NicoDevX** [sunitk/multitenancy-dynamic-tenant#5]
Hi, when i add a schema to the master_tenant table in my main database, it create a new master_tenant table in the customer tenant-database but i don't know why. i only should have one master_tenant in my main database?!

**Comment by sunitk** [comment]
Sorry for the late response, but I did not understand your situation completely. As I have said in my comments section, its best to create the schemas manually for every tenant you add.
