### ISSUE TITLE
How do I test this?

### ISSUE THREAD

**Issue by Koditect** [sunitk/multitenancy-dynamic-tenant#8]
Please provide sample sql scripts and user login information

**Comment by sunitk** [comment]
Please read [part 1](https://sunitkatkar.blogspot.com/2018/04/building-saas-style-multi-tenant-web.html) post first which explains how the multitenancy has been set up. Then [part 2](https://sunitkatkar.blogspot.com/2018/04/building-saas-style-multi-tenant-web2.html) explains how to set up the SQL scripts.

This example is so basic that creating the SQL scripts should actually be very simple. The whole point is to demonstrate how a master database table stores information about other tenants and then how Spring accesses the tenant databases.

This is not an issue and so I am closing it.
